apiVersion: v1
kind: Service
metadata:
  name: {{ include "vbilling.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vbilling.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "vbilling.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
